<a href="https://colab.research.google.com/github/anuhingankar9922-hub/-Python-Basic-Projects/blob/main/countries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
from google.colab import files
uploaded = files.upload()

Saving Countries_300_Rows.csv to Countries_300_Rows.csv

In [5]:
df = pd.read_csv("Countries_300_Rows.csv")

In [6]:
df.head()

     Country    Capital      Continent  Population  Area_km2  GDP_Billion_USD
0  Country_1  Capital_1           Asia      512345     10250             11.7
1  Country_2  Capital_2         Europe      524690     10500             13.4
2  Country_3  Capital_3         Africa      537035     10750             15.1
3  Country_4  Capital_4  North America      549380     11000             16.8
4  Country_5  Capital_5  South America      561725     11250             18.5

In [7]:
df.tail()

,Country,Capital,Continent,Population,Area_km2,GDP_Billion_USD
295,Country_296,Capital_296,Europe,4154120,84000,513.2
296,Country_297,Capital_297,Africa,4166465,84250,514.9
297,Country_298,Capital_298,North America,4178810,84500,516.6
298,Country_299,Capital_299,South America,4191155,84750,518.3
299,Country_300,Capital_300,Oceania,4203500,85000,520.0

In [11]:
df.shape

(300, 6)

In [8]:

df.columns

Index(['Country', 'Capital', 'Continent', 'Population', 'Area_km2',
       'GDP_Billion_USD'],
      dtype='object')

In [ ]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Country          300 non-null    object
 1   Capital          300 non-null    object
 2   Continent        300 non-null    object
 3   Population       300 non-null    int64
 4   Area_km2         300 non-null    int64
 5   GDP_Billion_USD  300 non-null    float64
dtypes: float64(1), int64(2), object(3)
memory usage: 14.2+ KB

In [ ]:

df.describe()

         Population      Area_km2  GDP_Billion_USD
count  3.000000e+02    300.000000       300.000000
mean   2.357922e+06  47625.000000       265.850000
std    1.070889e+06  21686.689466       147.469488
min    5.123450e+05  10250.000000        11.700000
25%    1.435134e+06  28937.500000       138.775000
50%    2.357922e+06  47625.000000       265.850000
75%    3.280711e+06  66312.500000       392.925000
max    4.203500e+06  85000.000000       520.000000

In [ ]:

df.dtypes

Country             object
Capital             object
Continent           object
Population           int64
Area_km2             int64
GDP_Billion_USD    float64
dtype: object

In [9]:

df.isnull().sum()

Country            0
Capital            0
Continent          0
Population         0
Area_km2           0
GDP_Billion_USD    0
dtype: int64

In [ ]:

df.nunique()

Country            300
Capital            300
Continent            6
Population         300
Area_km2           300
GDP_Billion_USD    300
dtype: int64

In [10]:

df.sample(5)

,Country,Capital,Continent,Population,Area_km2,GDP_Billion_USD
82,Country_83,Capital_83,South America,1524635,30750,151.1
24,Country_25,Capital_25,Asia,808625,16250,52.5
177,Country_178,Capital_178,North America,2697410,54500,312.6
176,Country_177,Capital_177,Africa,2685065,54250,310.9
39,Country_40,Capital_40,North America,993800,20000,78.0

In [ ]:

df["Continent"].value_counts()

Continent
Asia             50
Europe           50
Africa           50
North America    50
South America    50
Oceania          50
Name: count, dtype: int64